# Generated by Django 5.0.6 on 2024-06-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knihovna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('název', models.CharField(error_messages={'blank': 'Název knihovny je povinný údaj'}, help_text='Zadejte název knihovny', max_length=100, verbose_name='Název knihovny')),
                ('adresa', models.CharField(error_messages={'blank': 'Adresa knihovny je povinný údaj'}, help_text='Zadejte adresu knihovny', max_length=200, verbose_name='Adresa knihovny')),
                ('telefon', models.CharField(help_text='Zadejte telefonní číslo knihovny', max_length=15, verbose_name='Telefonní číslo')),
                ('email', models.EmailField(help_text='Zadejte emailovou adresu knihovny', max_length=254, verbose_name='Email knihovny')),
            ],
            options={
                'verbose_name': 'Knihovna',
                'verbose_name_plural': 'Knihovny',
                'ordering': ['název'],
            },
        ),
        migrations.CreateModel(
            name='Čtenář',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uživatelské_jméno', models.CharField(error_messages={'blank': 'Uživatelské jméno musí být vyplněno'}, help_text='Zadejte uživatelské jméno', max_length=80, verbose_name='Uživatelské jméno')),
                ('email', models.EmailField(error_messages={'blank': 'Emailová adresa musí být vyplněna'}, help_text='Zadejte emailovou adresu', max_length=254, verbose_name='Emailová adresa')),
                ('datum_registrace', models.DateField(auto_now_add=True, verbose_name='Datum registrace')),
                ('aktivní', models.BooleanField(default=True, verbose_name='Aktivní účet')),
            ],
            options={
                'verbose_name': 'Čtenář',
                'verbose_name_plural': 'Čtenáři',
                'ordering': ['uživatelské_jméno'],
            },
        ),
        migrations.CreateModel(
            name='Knihovník',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jméno', models.CharField(error_messages={'blank': 'Jméno knihovníka musí být vyplněno'}, help_text='Zadejte jméno knihovníka', max_length=80, verbose_name='Jméno knihovníka')),
                ('příjmení', models.CharField(error_messages={'blank': 'Příjmení knihovníka musí být vyplněno'}, help_text='Zadejte příjmení knihovníka', max_length=50, verbose_name='Příjmení knihovníka')),
                ('knihovna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektapp.knihovna', verbose_name='Knihovna')),
            ],
            options={
                'verbose_name': 'Knihovník',
                'verbose_name_plural': 'Knihovníci',
                'ordering': ['příjmení', 'jméno'],
            },
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_rezervace', models.DateField(auto_now_add=True, verbose_name='Datum rezervace')),
                ('stav', models.CharField(choices=[('čekající', 'Čekající'), ('vyzvednuto', 'Vyzvednuto')], default='čekající', max_length=20, verbose_name='Stav rezervace')),
                ('čtenář', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektapp.čtenář', verbose_name='Čtenář')),
            ],
            options={
                'verbose_name': 'Rezervace',
                'verbose_name_plural': 'Rezervace',
                'ordering': ['datum_rezervace'],
            },
        ),
        migrations.CreateModel(
            name='Půjčka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_půjčení', models.DateField(auto_now_add=True, verbose_name='Datum půjčení')),
                ('datum_vrácení', models.DateField(blank=True, null=True, verbose_name='Datum vrácení')),
                ('čtenář', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektapp.čtenář', verbose_name='Čtenář')),
            ],
            options={
                'verbose_name': 'Půjčka',
                'verbose_name_plural': 'Půjčky',
                'ordering': ['datum_půjčení'],
            },
        ),
    ]
